export enum UploadProcessStatusEnum {
  CONVERSION_PENDING = 'CONVERSION_PENDING',
  CONVERSION_STARTED = 'CONVERSION_STARTED',
  CONVERSION_COMPLETED = 'CONVERSION_COMPLETED',
  CONVERSION_FAILED = 'CONVERSION_FAILED',
}
